-- Migration number: 0002 generated by teenybase on 2026-02-17T08:07:15.237Z. Do not modify this file.

CREATE TABLE kv_store (
	key TEXT PRIMARY KEY NOT NULL, 
	value JSON NOT NULL, 
	expire TIMESTAMP
);