-- Migration number: 0003 generated by teenybase on 2026-02-17T08:50:12.965Z. Do not modify this file.

CREATE TABLE events (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	owner_id TEXT NOT NULL REFERENCES users(id), 
	title TEXT NOT NULL, 
	target_date TIMESTAMP NOT NULL, 
	start_date TIMESTAMP NOT NULL
);
CREATE INDEX idx_events_owner_id ON events (owner_id);
CREATE INDEX idx_events_target_date ON events (target_date);
CREATE TRIGGER tgr_events_raise_on_created_update BEFORE UPDATE OF created ON events BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;