-- Migration number: 0004 generated by teenybase on 2026-02-17T08:50:12.967Z. Do not modify this file.

DROP TABLE IF EXISTS notes;DROP TRIGGER IF EXISTS fts5_notes_idx_ai;
DROP TRIGGER IF EXISTS fts5_notes_idx_ad;
DROP TRIGGER IF EXISTS fts5_notes_idx_au;
DROP TABLE IF EXISTS fts5_notes_idx;